name: Remote SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$MY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $HOST_IP >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa $USER_NAME@$HOST_IP "echo Successfully connected to remote server"
        env:
          MY_KEY: ${{ secrets.MY_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_IP: ${{ secrets.HOST_IP }}

