name: Remote SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.MY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ variables.HOST_IP }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ variables.USER_NAME }}@${{ variables.HOST_IP }} "echo Successfully connected to remote server"

