name: Remote SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "${{ secrets.MY_KEY }}" > key.pem
          chmod 600 key.pem
          ssh-keyscan -H 89.169.133.122 >> ~/.ssh/known_hosts
          ssh -i key.pem dm@89.169.133.122 "echo Successfully connected to a remote server"
