name: Remote SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MY_KEY }}
      - name: Setup SSH
        env: 
          USER_NAME: ${{ vars.USER_NAME }}
          HOST_IP: ${{ vars.HOST_IP }}
        run: |
          ssh -o "StrictHostKeyChecking no" $USER_NAME@$HOST_IP "pwd"
      - name: List files
        run: |
          ssh -o "StrictHostKeyChecking no" $USER_NAME@$HOST_IP "ls -l"
