name: Remote SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          touch MY_KEY_FL
          echo $MY_KEY > MY_KEY_FL
          ssh -i MY_KEY_FL $USER_NAME@$HOST_IP "echo Successfully connected to remote server"
        env:
          MY_KEY: ${{ vars.MY_KEY }}
          USER_NAME: ${{ vars.USER_NAME }}
          HOST_IP: ${{ vars.HOST_IP }}

