name: Deploy
on:
 workflow_dispatch

env:
 SERVER_HOST: 89.169.133.122
 SERVER_USER: dm
 SERVER_PATH: /root/github-test

jobs:

 deploy:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3

     # Install ssh key
     - name: Install SSH Key
       uses: Saiz-web/ssh-key-action@v2.3.1
       with:
         key: "${{ secrets.MY_KEY }}"
         known_hosts: "just-a-placeholder-so-we-dont-get-errors"
         
     - name: Generate auth hosts
       run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

     - name: Run command
       run: ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'pwd' 
